CREATE DATABASE GestionDeEmpleados
USE GestionDeEmpleados

CREATE TABLE PERSONA(
idPersona INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(200) NOT NULL,
estado VARCHAR(50) NOT NULL
)

CREATE TABLE EMPLEADO(
idEmpleado INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
idPersona INT NOT NULL,
puesto VARCHAR(100) NOT NULL,
salario MONEY NOT NULL,
fechaContratacion DATETIME NOT NULL,
FOREIGN KEY (idPersona) REFERENCES PERSONA (idPersona)
)

INSERT INTO PERSONA VALUES ('Rocio', 'Cruz Zambrana', 'Activo');
INSERT INTO PERSONA VALUES ('Gerardo', 'Velasquez Camacho', 'Activo');
INSERT INTO PERSONA VALUES ('Jorge', 'Aguilera Pantoja', 'Activo');
SELECT * FROM PERSONA

INSERT INTO EMPLEADO VALUES (1, 'Gerente', '5000', '2022-02-01 14:00:00');
INSERT INTO EMPLEADO VALUES (2, 'Contador', '4000', '2022-02-01 14:01:00');
INSERT INTO EMPLEADO VALUES (3, 'Genrente de Marketing', '4000', '2022-02-02 14:00:00');
SELECT * FROM EMPLEADO