CREATE DATABASE GestionDeEmpleados
USE GestionDeEmpleados

CREATE TABLE PERSONA(
idPersona INT NOT NULL PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(200) NOT NULL,
estado VARCHAR(50) NOT NULL
)

CREATE TABLE EMPLEADO(
idEmpleado INT NOT NULL PRIMARY KEY,
idPersona INT NOT NULL,
puesto VARCHAR(100) NOT NULL,
salario MONEY NOT NULL,
fechaContratacion DATETIME NOT NULL
)